### ISSUE TITLE
InvalidRange: The requested range is not satisfiable (HTTP error response code 416)

### ISSUE THREAD

**Issue by MrBemd** [about14sheep/s3-readstream#1]
In case the **_currentCursorPosition** is the same as the **adjustedRange** you will get an error from S3: "InvalidRange: The requested range is not satisfiable". This will occur in cases that the size of the file is equal to 1024 * 64 (default **_s3DataRange**) + the steps taken to stream the file.

For example, if we have a file with a size of 327.685 bytes the requests sent are as follows:

`bytes=0-65536`
`bytes=65537-131073`
`bytes=131074-196610`
`bytes=196611-262147`
`bytes=262148-327684`
`bytes=327685-327685`

This last request will lead to the InvalidRange error. As byte offsets start at zero (https://www.rfc-editor.org/rfc/rfc7233#section-2.1) the request should not be sent at all.

This can be fixed by changing the code on line 77:

`if (this._currentCursorPosition >= this._maxContentLength) {`
`    this.push(null);`
`} else {`
`   ...`
`}`

Do you agree with the proposed solution?

**Comment by about14sheep** [comment]
I do agree. After reading the docs you shared it appears the error comes from `this._maxContentLength` being the number of bytes and while the _range_ of bytes is actually `0 - this._maxContentLength - 1`. A classic case of 0-indexing being missed. Thanks
