### ISSUE TITLE
InvalidRange: Can't read empty file

### ISSUE THREAD

**Issue by astrioh** [about14sheep/s3-readstream#4]
In case the file's ContentLength is 0 bytes S3ReadStream will form an invalid header "bytes=0-0" and you will get HTTP error with response code 416 `InvalidRange: The requested range is not satisfiable`.

The proposed solution can be seen here: https://github.com/about14sheep/s3-readstream/pull/3

**Comment by about14sheep** [comment]
this is fixed in version 1.1.3. Please see attached Pull Request conversation. I am closing this issue
